In [1]:
import pandas as pd

In [29]:
def load_dataframes(id: str):
    indonesia_orig = pd.read_csv("datasets/covid_indonesia.csv")
    indonesia_checkpoints = [
        pd.read_csv(f"dataset_checkpoints/covid19-indonesia_modified_round{i}_{id}.csv") for i in range(2)
    ]
    # indonesia_final = pd.read_csv(f"dataset_checkpoints/covid19-indonesia_modified_round2_{id}.csv")

    global_orig = pd.read_csv("datasets/covid_global.csv")
    global_checkpoints = [
        pd.read_csv(f"dataset_checkpoints/covid19-global_modified_round{i}_{id}.csv") for i in range(2)
    ]
    # global_final = pd.read_csv(f"dataset_checkpoints/covid19-global_modified_round2_{id}.csv")

    return indonesia_orig, indonesia_checkpoints, global_orig, global_checkpoints

In [30]:
id = 1791969010.8668191
indonesia_orig, indonesia_checkpoints, global_orig, global_checkpoints = load_dataframes(id)

In [31]:
indonesia_orig.head()

,Unnamed: 0,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,NaN,NaN
1,1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.0,1.0
2,2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3,3/2/2020,ID-RI,Riau,1,0,0,1,1,0,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,NaN,NaN
4,4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.0,1.0

In [32]:
global_orig.head()

,Unnamed: 0,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [33]:
indonesia_checkpoints[0].head()

,Unnamed: 0,row_index,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,total_cases,...,Latitude,new_cases_per_million,total_cases_per_million,new_deaths_per_million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,0,0,2020-03-01,ID-JK,Indonesia,2,0,0,2,39,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,NaN,NaN
1,1,1,2020-03-02,ID-JK,Indonesia,2,0,0,2,41,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.0,1.0
2,2,2,2020-03-02,IDN,Indonesia,2,0,0,2,2,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3,3,2020-03-02,ID-RI,Indonesia,1,0,0,1,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,NaN,NaN
4,4,4,2020-03-03,ID-JK,Indonesia,2,0,0,2,43,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.0,1.0

In [34]:
indonesia_checkpoints[1].head()

,Unnamed: 0.1,Unnamed: 0,row_index,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,...,Latitude,new_cases_per_million,total_cases_per_million,new_deaths_per_million,total_deaths_per_million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,0,0,0,2020-03-01,IDN,Indonesia,2,0,0,2,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,NaN,NaN
1,1,1,1,2020-03-02,IDN,Indonesia,2,0,0,2,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.0,1.0
2,2,2,2,2020-03-02,IDN,Indonesia,2,0,0,2,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3,3,3,2020-03-02,IDN,Indonesia,1,0,0,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,NaN,NaN
4,4,4,4,2020-03-03,IDN,Indonesia,2,0,0,2,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.0,1.0

In [36]:
global_orig.head()

,Unnamed: 0,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [37]:
global_checkpoints[0].head()

,Unnamed: 0,row_index,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,0,0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,1,1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,2,2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,3,3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,4,4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [38]:
global_checkpoints[1].head()

,Unnamed: 0.1,Unnamed: 0,row_index,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,0,0,0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,1,1,1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,2,2,2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,3,3,3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,4,4,4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [13]:
harm_instructions = [pd.read_csv(f"harmonization_instructions_round_{i}_<built-in function id>.csv") for i in range(3)]

In [26]:
check_idx = 2
instructions_global = harm_instructions[check_idx].loc[harm_instructions[check_idx]["dataset"] == "covid19-global"]
instructions_ind = harm_instructions[check_idx].loc[harm_instructions[check_idx]["dataset"] == "covid19-indonesia"]

instructions_global["transformation"].values

array(['No transformation required – values already follow the ISO\u202f8601 YYYY‑MM‑DD format.',
       'No transformation needed; values already conform to ISO\u202f3166‑1 alpha‑3 codes.',
       'Map each entry to a DBpedia place entity. Keep entries that are countries, continents or regions as place names, but ensure they are spelled consistently (e.g., "Afghanistan", "Africa"). Optionally add a column with the matching DBpedia URI (e.g., https://dbpedia.org/resource/Afghanistan).',
       'Replace any `nan` entries with `null` (or remove the rows). Ensure all values are spelled exactly as one of the accepted continent names (e.g., map synonyms like "America" → "North America"). No change to the URI is needed as it already matches the selected DBpedia URI.',
       'No transformation required – the data already conforms to the selected numeric URI. Ensure the column is stored as a non‑negative number (integer or float).',
       'No transformation needed – data already conforms to XSD Number. Ensure NaN values are stored as null in the unified schema.',
       'No transformation required; the data already conforms to the selected XSD Number type and represents total case counts.',
       'No transformation needed – values already conform to XSD Number and the selected feature semantics.',
       'Cast the values to non‑negative integers (e.g., round or truncate) to match the expected integer count of cases.',
       'Replace NaN values with a null/NA indicator (or impute as 0 if appropriate). Cast all values to integer type and ensure they are >=\u202f0.',
       'No transformation needed; the data already conforms to a non‑negative XSD number representing cases per million.',
       'Rename the column to `new_cases_per_million` (snake_case) if it is not already, and ensure the values are stored as a numeric type compatible with XSD Number (e.g., float). No unit conversion is required because the data already represent cases per million.',
       'Convert the column to a numeric (float) type, replace NaN values with null (or a designated missing‑value token) so that all entries comply with the non‑negative number requirement.',
       'No transformation required; ensure missing entries remain as NaN or are omitted, and all values are stored as decimal numbers (float).',
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan], dtype=object)

In [27]:
instructions_ind["transformation"].values

array(['Convert the month‑day‑year strings (M/D/YYYY) to ISO\u202f8601 format (YYYY‑MM‑DD). For example, "3/1/2020" → "2020-03-01".',
       'No transformation needed; values already conform to ISO\u202f3166‑2 subdivision codes or ISO\u202f3166‑1 alpha‑3.',
       'Treat sub‑national entries such as "DKI Jakarta" and "Jawa Barat" as place names. Normalize case and map each to its DBpedia place URI (e.g., https://dbpedia.org/resource/DKI_Jakarta). Ensure all values conform to the same place‑name convention.',
       'Update the feature URI from `http://xmlns.com/foaf/0.1/Person` to the selected DBpedia URI `http://dbpedia.org/resource/Continent`. The existing value "Asia" already conforms to the allowed value set, so no value transformation is required.',
       'No transformation required – the data already conforms to the selected numeric URI. Ensure the column name is normalized to the unified feature name "population" and stored as a non‑negative number.',
       'No transformation needed – data already conforms to XSD Number. Ensure values are stored as numeric and handle NaN as null.',
       'No transformation required; the data already conforms to the selected XSD Number type and represents total case counts.',
       'No transformation needed – values already conform to XSD Number and the selected feature semantics.',
       'No transformation needed; values already conform to non‑negative integer counts.',
       'Confirm that all values are stored as integers (no floating‑point representation) and that no negative numbers appear.',
       'No transformation needed; the data already conforms to a non‑negative XSD number representing cases per million.',
       'Rename the column to `new_cases_per_million` (snake_case) and confirm the column type is numeric (XSD Number). No further transformation needed as the data already match the target granularity.',
       'Ensure the column is stored as a numeric (float) type; no further transformation is required as all values already satisfy the non‑negative number constraint.',
       'No transformation required; keep the values as decimal numbers (float) matching the XSD Number type.',
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
      dtype=object)